### ISSUE TITLE
Huge memory consumtion

### ISSUE THREAD

**Issue by azzamsa** [flatpak/xdg-dbus-proxy#51]
Hi.

![image](https://github.com/flatpak/xdg-dbus-proxy/assets/17734314/6b351d38-253c-4915-ab78-fbfd1e95dfdd)

```
Flatpak 1.14.4
Debian GNU/Linux 12 (bookworm)
Wayland
```

Related: https://github.com/flatpak/flatpak/issues/3386

**Comment by azzamsa** [comment]
> I noticed that for me it only affects applications that make heavy use of the `org.freedesktop.Flatpak` portal, such as [Black Box](https://flathub.org/de/apps/com.raggesilver.BlackBox). But it's entirely possible that this is just a coincidence.

Yes, I am using BlackBox. I also plan to replace it because it uses a considerable amount of memory just to run the terminal app. How to know which app uses org.freedesktop.Flatpak portal?

**Comment by yomono** [comment]
Well I'm using Black Box too so at least we're 3 of 3 so far.
Of course I'm willing to change the app since 10gb for a terminal it's a little bit excessive but there's definitely some root common cause

**Comment by azzamsa** [comment]
>  but you could use this quick and dirty command:

```
🦄 flatpak list --app --columns=ref:f | xargs -i sh -c "flatpak info --show-ref --show-permissions {} | grep -zF org.freedesktop.Flatpak=talk | head -n 1"
app/com.github.johnfactotum.Foliate/x86_64/stable
app/com.github.liferooter.textpieces/x86_64/stable
app/com.raggesilver.BlackBox/x86_64/stable
app/org.wezfurlong.wezterm/x86_64/stable
```

**Comment by RomanAverin** [comment]
I have the same problem and it started after Black Box 0.14 update

**Comment by ashrude** [comment]
![image](https://github.com/flatpak/xdg-dbus-proxy/assets/49853479/177b1bb3-3d2f-44c2-8502-2c42fe035425)
Wow, I'm using blackbox as well and didn't expect such a dramatic amount of resources to be freed when I closed it.

**Comment by raggesilver** [comment]
Hey, I think this is an issue with Black Box. Unless someone can confirm this happens with another program, I suggest closing this issue in favor of https://gitlab.gnome.org/raggesilver/blackbox/-/issues/322.

**Comment by qwertychouskie** [comment]
This also affects Mission Center: https://gitlab.com/mission-center-devs/mission-center/-/issues/61#note_1584564638

**Comment by joaoherrera** [comment]
> While I think it's not unlikely that there is a bug in BlackBox that causes this, I don't think the bug is _only_ on the BlackBox side for the following reasons:
> 
> * The excessive resource consumption happens in the `flatpak-session-helper` and `xdg-dbus-proxy` processes.
> * The enormous amount of memory used by `flatpak-session-helper` is not reclaimed when BlackBox is closed.
> 
> At least for the memory usage of these two processes, I think even a buggy application shouldn't be able to cause that much memory usage, especially if it's not reclaimed when the buggy application is closed. For CPU usage, of course, it's not so simple.

You're right. I don't have BlackBox installed and I'm facing the same issues. In my case, it seems that the problem is related to the Telegram Desktop app, and I installed it via flatpak.

**Comment by rstanuwijaya** [comment]
Can confirm also getting the same issue with BlackBox installed

**Comment by opqriu** [comment]
This problem happens all too often with Blackbox. Yesterday, today.

And years ago... It also happened when I was working with flatpak-Audacity on a low-end system. At that time, a clean install of audacity (not flatpak) solved the problem.

**Comment by mardy** [comment]
I think this is fixed here: https://github.com/sailfishos/xdg-dbus-proxy/blob/master/rpm/0001-Fix-GVariant-reference-leaks.patch

**Comment by qwertychouskie** [comment]
It may very well be the fix.  Is there any reason this patch was never upstreamed?

**Comment by qwertychouskie** [comment]
It may very well be the fix. @spiiroin Is there any reason your patch (`0001-Fix-GVariant-reference-leaks.patch`) was never upstreamed?

**Comment by spiiroin** [comment]
> Is there any reason your patch (`0001-Fix-GVariant-reference-leaks.patch`) was never upstreamed?

@qwertychouskie Nope, unless you count the usual: slipping through the cracks because this was a side track bug hunt while being busy with something else...

**Comment by sviperz** [comment]
So, what is a proper way to fix this issue now in the OS?

**Comment by matthiasclasen** [comment]
The fix was merged, closing this

**Comment by sviperz** [comment]
Assuming I have Ubuntu 24.04, how can I have this fix as soon as possible except building from source?

**Comment by LordManhattan** [comment]
It's still an issue. Looks like the source app is StreamController (Flatpak), and I have no idea why it's using this much RAM since it's never done it before (that I've noticed). Running Fedora WS 40.



![Screenshot from 2024-07-11 20-03-36](https://github.com/flatpak/xdg-dbus-proxy/assets/7291676/a7dd7c75-f320-4db4-850c-058f44c0920a)

**Comment by TingPing** [comment]
@LordManhattan Because this fix isn't in a release yet. I believe a new release will be coming very soon.

**Comment by waveform80** [comment]
> Assuming I have Ubuntu 24.04, how can I have this fix as soon as possible except building from source?

I've opened [LP: #2083258](https://bugs.launchpad.net/ubuntu/+source/xdg-dbus-proxy/+bug/2083258) to track this in Ubuntu 24.04; please refer to that bug if you're an Ubuntu user

**Comment by akusokuzan** [comment]
I haven't tried the fix yet anyone report on how its going I'm having the same issue.

![Image](https://github.com/user-attachments/assets/8a350fa8-f1b8-46f3-81e3-5e0ffd7a6acb)

**Comment by Jckf** [comment]
Mint 21.3
![Image](https://github.com/user-attachments/assets/717738b7-9a7f-4ce4-b0e9-285cba55b9f5)

**Comment by oakeef** [comment]
Linux Mint 22.1
Feels like a memory leak to me as it just grows and grows over time until the system is reset
![Image](https://github.com/user-attachments/assets/6903308a-c374-46fb-b645-b0483d30a209)

**Comment by crotron** [comment]
> Same here Linux Mint 22.1
> 
> is there any way to restart the xdg-dbus-proxy without causing any issues and reset its memory allocation?

I've been running `pkill xdg-dbus-proxy; sleep 10; flatpak run com.rustdesk.RustDesk` whenever I see it using too much memory. I've been doing this for the past couple of months and haven't personally encountered any issues from doing so, as of yet.

**Comment by Bonjour123** [comment]
<img width="287" height="370" alt="Image" src="https://github.com/user-attachments/assets/4796bf03-1707-4828-8a05-ec99489f5665" />

Still happening, any plan to fix it soon ?
